[package]
name = "brilliance"
version = "3.0.0"
authors = ["Arne Vansteenkiste <barnex@gmail.com>"]
edition = "2018"

[dependencies]
image = "0.23"
rand = "0.7.3"
rand_xoshiro = "0.4"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "benchmarks"
harness = false